#define F(NAME,TARGET) class NAME { \
    allowedTargets = TARGET; \
};

#define ANYONE 0
#define CLIENT 1
#define SERVER 2
#define HC HC_Life

class CfgRemoteExec {
    class Functions {
        mode = 1;
        jip = 0;

        /* Client only functions */
        F(life_fnc_addVehicle2Chain,CLIENT)
        F(life_fnc_adminid,CLIENT)
        F(life_fnc_admininfo,CLIENT)
        F(life_fnc_bountyReceive,CLIENT)
        F(life_fnc_copLights,CLIENT)
        F(life_fnc_copSearch,CLIENT)
        F(life_fnc_copSiren,CLIENT)
        F(life_fnc_freezePlayer,CLIENT)
        F(life_fnc_gangCreated,CLIENT)
        F(life_fnc_gangDisbanded,CLIENT)
        F(life_fnc_gangInvite,CLIENT)
        F(life_fnc_garageRefund,CLIENT)
        F(life_fnc_giveDiff,CLIENT)
        F(life_fnc_hideObj,CLIENT)
        F(life_fnc_impoundMenu,CLIENT)
        F(life_fnc_jail,CLIENT)
        F(life_fnc_jailMe,CLIENT)
        F(life_fnc_knockedOut,CLIENT)
        F(life_fnc_lightHouse,CLIENT)
        F(life_fnc_mediclights,CLIENT)
        F(life_fnc_medicRequest,CLIENT)
        F(life_fnc_medicSiren,CLIENT)
        F(life_fnc_moveIn,CLIENT)
        F(life_fnc_pickupItem,CLIENT)
        F(life_fnc_pickupMoney,CLIENT)
        F(life_fnc_receiveItem,CLIENT)
        F(life_fnc_removeLicenses,CLIENT)
        F(life_fnc_restrain,CLIENT)
        F(life_fnc_revived,CLIENT)
        F(life_fnc_robPerson,CLIENT)
        F(life_fnc_robReceive,CLIENT)
        F(life_fnc_searchClient,CLIENT)
        F(life_fnc_seizeClient,CLIENT)
        F(life_fnc_soundDevice,CLIENT)
        F(life_fnc_spikeStripEffect,CLIENT)
        F(life_fnc_tazeSound,CLIENT)
        F(life_fnc_ticketPaid,CLIENT)
        F(life_fnc_ticketPrompt,CLIENT)
        F(life_fnc_vehicleAnimate,CLIENT)
        F(life_fnc_wantedList,CLIENT)
        F(life_fnc_wireTransfer,CLIENT)
        F(SOCK_fnc_dataQuery,CLIENT)
        F(SOCK_fnc_insertPlayerInfo,CLIENT)
        F(SOCK_fnc_updateRequest,CLIENT)
        F(SOCK_fnc_requestReceived,CLIENT)
        F(TON_fnc_clientGangKick,CLIENT)
        F(TON_fnc_clientGangLeader,CLIENT)
        F(TON_fnc_clientGangLeft,CLIENT)
        F(TON_fnc_clientGetKey,CLIENT)
        F(TON_fnc_clientMessage,CLIENT)
        F(TON_fnc_player_query,CLIENT)
        F(ALF_fnc_updateForfait,CLIENT)
        F(ALF_fnc_menuNokia,CLIENT)
        F(ALF_fnc_receptionSmsPhone,CLIENT)
        F(ALF_fnc_updateSmsNokia,CLIENT)
        F(ALF_fnc_updateSmsiPhone,CLIENT)
        F(ALF_fnc_updateSmsSony,CLIENT)
        F(ALF_fnc_ringPlayer,CLIENT)
        F(ALF_fnc_iamBusy,CLIENT)
        F(ALF_fnc_afterTransferCompteBancaire,CLIENT)
        F(ALF_fnc_badTransferCompteBancaire,CLIENT)
        F(ALF_fnc_infoTransferCompteBancaire,CLIENT)
        F(ALF_fnc_receiveMoney,CLIENT)
        F(ALF_fnc_licenseCheck,CLIENT)
        F(ALF_fnc_licensesRead,CLIENT)
        F(ALF_fnc_doMsg,CLIENT)
        F(ALF_fnc_p_removeMagazine,CLIENT)
        F(ALF_fnc_resultPlaque,CLIENT)
        F(life_fnc_dispoVehicle,CLIENT)
        F(ALF_fnc_buyStation,CLIENT)
        F(ALF_fnc_initStation,CLIENT)
        F(ALF_fnc_sellStation,CLIENT)
        F(ALF_fnc_stationMenu,CLIENT)
        F(ALF_fnc_doCopCall,CLIENT)
        F(ALF_fnc_resetCall,CLIENT)

        /* Server only functions */
        F(bis_fnc_execvm,SERVER)
        F(DB_fnc_insertRequest,SERVER)
        F(DB_fnc_queryRequest,SERVER)
        F(DB_fnc_updatePartial,SERVER)
        F(DB_fnc_updateRequest,SERVER)
        F(life_fnc_jailSys,SERVER)
        F(life_fnc_wantedAdd,SERVER)
        F(life_fnc_wantedBounty,SERVER)
        F(life_fnc_wantedCrimes,SERVER)
        F(life_fnc_wantedFetch,SERVER)
        F(life_fnc_wantedProfUpdate,SERVER)
        F(life_fnc_wantedRemove,SERVER)
        F(SPY_fnc_cookieJar,SERVER)
        F(SPY_fnc_observe,SERVER)
        F(TON_fnc_addmobilier,SERVER)
        F(TON_fnc_addHouse,SERVER)
        F(TON_fnc_chopShopSell,SERVER)
        F(TON_fnc_cleanupRequest,SERVER)
        F(TON_fnc_deleteDBmobilier,SERVER)
        F(TON_fnc_getID,SERVER)
        F(TON_fnc_getVehicles,SERVER)
        F(TON_fnc_insertGang,SERVER)
        F(TON_fnc_managesc,SERVER)
        F(TON_fnc_pickupAction,SERVER)
        F(TON_fnc_removeGang,SERVER)
        F(TON_fnc_sellHouse,SERVER)
        F(TON_fnc_sellHousemobilier,SERVER)
        F(TON_fnc_setObjVar,SERVER)
        F(TON_fnc_spawnVehicle,SERVER)
        F(TON_fnc_spikeStrip,SERVER)
        F(TON_fnc_updateGang,SERVER)
        F(TON_fnc_updateHousemobiliers,SERVER)
        F(TON_fnc_updateHouseTrunk,SERVER)
        F(TON_fnc_vehicleCreate,SERVER)
        F(TON_fnc_vehicleDelete,SERVER)
        F(TON_fnc_vehicleStore,SERVER)
        F(TON_fnc_vehicleUpdate,SERVER)
        F(TON_fnc_recupkeyforHC,SERVER)
        F(TON_fnc_addkeyforHC,SERVER)
		F(TON_fnc_keyManagement,SERVER)

        /* HeadlessClient only functions */
        F(HC_fnc_addMobilier,HC)
        F(HC_fnc_addHouse,HC)
        F(HC_fnc_chopShopSell,HC)
        F(HC_fnc_deleteDBmobilier,HC)
        F(HC_fnc_getVehicles,HC)
        F(HC_fnc_insertGang,HC)
        F(HC_fnc_insertRequest,HC)
        F(HC_fnc_insertVehicle,HC)
        F(HC_fnc_jailSys,HC)
        F(HC_fnc_queryRequest,HC)
        F(HC_fnc_removeGang,HC)
        F(HC_fnc_sellHouse,HC)
        F(HC_fnc_sellHousemobilier,HC)
        F(HC_fnc_spawnVehicle,HC)
        F(HC_fnc_spikeStrip,HC)
        F(HC_fnc_updateGang,HC)
        F(HC_fnc_updateHousemobiliers,HC)
        F(HC_fnc_updatePartial,HC)
        F(HC_fnc_updateRequest,HC)
        F(HC_fnc_vehicleCreate,HC)
        F(HC_fnc_vehicleDelete,HC)
        F(HC_fnc_vehicleStore,HC)
        F(HC_fnc_vehicleUpdate,HC)
        F(HC_fnc_wantedAdd,HC)
        F(HC_fnc_wantedBounty,HC)
        F(HC_fnc_wantedCrimes,HC)
        F(HC_fnc_wantedFetch,HC)
        F(HC_fnc_wantedProfUpdate,HC)
        F(HC_fnc_wantedRemove,HC)
        F(HC_fnc_receivekeyofServer,HC)
        F(HC_fnc_calculBourse,HC)
        F(HC_fnc_initBourse,HC)
        F(HC_fnc_loggedBourse,HC)
        F(HC_fnc_saveBourse,HC)
        F(HC_fnc_updateBourse,HC)
        F(HC_fnc_buyForfait,HC)
        F(HC_fnc_removeForfait,HC)
        F(HC_fnc_updateContactsPhone,HC)
        F(HC_fnc_sendSmsPhone,HC)
        F(HC_fnc_loadSmsNokia,HC)
        F(HC_fnc_loadSmsiPhone,HC)
        F(HC_fnc_loadSmsSony,HC)
        F(HC_fnc_deleteSmsNokia,HC)
        F(HC_fnc_deleteSmsiPhone,HC)
        F(HC_fnc_FirstJoinServer,HC)
        F(HC_fnc_achatCompteBancaire,HC)
        F(HC_fnc_transferExtCompteBancaire,HC)
        F(HC_fnc_cbParametre,HC)
        F(HC_fnc_insureVehicles,HC)
        F(HC_fnc_fonderieSystem,HC)
        F(HC_fnc_recherchePlaque,HC)
        F(HC_fnc_dispoVehicle,HC)
        F(HC_fnc_buyVehicle,HC)
        F(HC_fnc_addStation,HC)
        F(HC_fnc_fetchPlayerStations,HC)
        F(HC_fnc_initStation,HC)
        F(HC_fnc_sellStation,HC)
        F(HC_fnc_poserC4,HC)
        F(HC_fnc_poserPc,HC)

        /* Functions for everyone */
        F(life_fnc_animSync,ANYONE)
        F(life_fnc_broadcast,ANYONE)
        F(life_fnc_colorVehicle,ANYONE)
        F(life_fnc_corpse,ANYONE)
        F(life_fnc_demoChargeTimer,ANYONE)
        F(life_fnc_flashbang,ANYONE)
        F(life_fnc_jumpFnc,ANYONE)
        F(life_fnc_lockVehicle,ANYONE)
        F(life_fnc_pulloutVeh,ANYONE)
        F(life_fnc_pushFunction,ANYONE)
        F(life_fnc_say3D,ANYONE)
        F(life_fnc_setFuel,ANYONE)
        F(life_fnc_simDisable,ANYONE)
        F(SPY_fnc_notifyAdmins,ANYONE)
        F(ALF_fnc_updateClientBourse,ANYONE)
        F(ALF_fnc_preReceptionSmsPhone,ANYONE)
        F(ALF_fnc_switchMove,ANYONE)

    };

    class Commands {
        mode = 1;
        jip = 0;

        F(addHandgunItem,ANYONE)
        F(addMagazine,ANYONE)
        F(addPrimaryWeaponItem,ANYONE)
        F(addWeapon,ANYONE)
        F(setFuel,ANYONE)
    };
};